author: robinmonjo@gmail.com
description: >
  Command line tool to pull and push docker image on the docker hub (no docker needed)

filesets:
  includes:
    - README.md
  excludes:
    - \.git
  depth: 3

settings:
  build: |
    sh vendor.sh && export GOPATH=$GOPATH:`pwd`/vendor && go install -v
